version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: bookmark-application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root@123

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookmark-application
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root@123
